# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "active-x-obfuscator-0.0.1" = {
      name = "active-x-obfuscator";
      packageName = "active-x-obfuscator";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/active-x-obfuscator/-/active-x-obfuscator-0.0.1.tgz";
        sha1 = "089b89b37145ff1d9ec74af6530be5526cae1f1a";
      };
    };
    "async-0.1.15" = {
      name = "async";
      packageName = "async";
      version = "0.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.1.15.tgz";
        sha1 = "2180eaca2cf2a6ca5280d41c0585bec9b3e49bd3";
      };
    };
    "base64id-0.1.0" = {
      name = "base64id";
      packageName = "base64id";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64id/-/base64id-0.1.0.tgz";
        sha1 = "02ce0fdeee0cef4f40080e1e73e834f0b1bfce3f";
      };
    };
    "batch-0.5.0" = {
      name = "batch";
      packageName = "batch";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/batch/-/batch-0.5.0.tgz";
        sha1 = "fd2e05a7a5d696b4db9314013e285d8ff3557ec3";
      };
    };
    "buffer-crc32-0.2.1" = {
      name = "buffer-crc32";
      packageName = "buffer-crc32";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-crc32/-/buffer-crc32-0.2.1.tgz";
        sha1 = "be3e5382fc02b6d6324956ac1af98aa98b08534c";
      };
    };
    "bytes-0.2.1" = {
      name = "bytes";
      packageName = "bytes";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-0.2.1.tgz";
        sha1 = "555b08abcb063f8975905302523e4cd4ffdfdf31";
      };
    };
    "commander-1.3.2" = {
      name = "commander";
      packageName = "commander";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-1.3.2.tgz";
        sha1 = "8a8f30ec670a6fdd64af52f1914b907d79ead5b5";
      };
    };
    "commander-2.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.1.0.tgz";
        sha1 = "d121bbae860d9992a3d517ba96f56588e47c6781";
      };
    };
    "connect-2.12.0" = {
      name = "connect";
      packageName = "connect";
      version = "2.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect/-/connect-2.12.0.tgz";
        sha1 = "31d8fa0dcacdf1908d822bd2923be8a2d2a7ed9a";
      };
    };
    "connect-3.7.0" = {
      name = "connect";
      packageName = "connect";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect/-/connect-3.7.0.tgz";
        sha512 = "ZqRXc+tZukToSNmh5C2iWMSoV3X1YUcPbqEM4DkEG5tNQXrQUZCNVGGv3IuicnkMtPfGf3Xtp8WCXs295iQ1pQ==";
      };
    };
    "connect-cache-0.2.2" = {
      name = "connect-cache";
      packageName = "connect-cache";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect-cache/-/connect-cache-0.2.2.tgz";
        sha1 = "87e54cba68b7fe5826b39aa6d571e11b3417d03d";
      };
    };
    "cookie-0.1.0" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.1.0.tgz";
        sha1 = "90eb469ddce905c866de687efc43131d8801f9d0";
      };
    };
    "cookie-signature-1.0.1" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.1.tgz";
        sha1 = "44e072148af01e6e8e24afbf12690d68ae698ecb";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "debug-0.8.1" = {
      name = "debug";
      packageName = "debug";
      version = "0.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-0.8.1.tgz";
        sha1 = "20ff4d26f5e422cb68a1bacbbb61039ad8c1c130";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "express-3.4.7" = {
      name = "express";
      packageName = "express";
      version = "3.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-3.4.7.tgz";
        sha1 = "3b939c47d2aa44dfecf77d50da2123c5bd313366";
      };
    };
    "finalhandler-1.1.2" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-1.1.2.tgz";
        sha512 = "aAWcW57uxVNrQZqFXjITpW3sIUQmHGG3qSb9mUah9MgMC4NeWhNOlNjXEYq3HjRAvL6arUviZGGJsBg6z0zsWA==";
      };
    };
    "fresh-0.2.0" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.2.0.tgz";
        sha1 = "bfd9402cf3df12c4a4c310c79f99a3dde13d34a7";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "js-md5-0.4.2" = {
      name = "js-md5";
      packageName = "js-md5";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-md5/-/js-md5-0.4.2.tgz";
        sha1 = "8a1231e60ab392a6d3a75db6d532ec0c59667bc3";
      };
    };
    "keypress-0.1.0" = {
      name = "keypress";
      packageName = "keypress";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz";
        sha1 = "4a3188d4291b66b4f65edb99f806aa9ae293592a";
      };
    };
    "log4js-0.6.9" = {
      name = "log4js";
      packageName = "log4js";
      version = "0.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/log4js/-/log4js-0.6.9.tgz";
        sha1 = "2e327189c1c0dec17448ec5255f58cd0fddf4596";
      };
    };
    "merge-descriptors-0.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-0.0.1.tgz";
        sha1 = "2ff0980c924cf81d0b5d1fb601177cb8bb56c0d0";
      };
    };
    "methods-0.1.0" = {
      name = "methods";
      packageName = "methods";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-0.1.0.tgz";
        sha1 = "335d429eefd21b7bacf2e9c922a8d2bd14a30e4f";
      };
    };
    "mime-1.2.11" = {
      name = "mime";
      packageName = "mime";
      version = "1.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.2.11.tgz";
        sha1 = "58203eed86e3a5ef17aed2b7d9ebd47f0a60dd10";
      };
    };
    "mkdirp-0.3.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz";
        sha1 = "de3e5f8961c88c787ee1368df849ac4413eca8d7";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "multiparty-2.2.0" = {
      name = "multiparty";
      packageName = "multiparty";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/multiparty/-/multiparty-2.2.0.tgz";
        sha1 = "a567c2af000ad22dc8f2a653d91978ae1f5316f4";
      };
    };
    "nan-1.0.0" = {
      name = "nan";
      packageName = "nan";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-1.0.0.tgz";
        sha1 = "ae24f8850818d662fcab5acf7f3b95bfaa2ccf38";
      };
    };
    "negotiator-0.3.0" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.3.0.tgz";
        sha1 = "706d692efeddf574d57ea9fb1ab89a4fa7ee8f60";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "options-0.0.6" = {
      name = "options";
      packageName = "options";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/options/-/options-0.0.6.tgz";
        sha1 = "ec22d312806bb53e731773e7cdaefcf1c643128f";
      };
    };
    "parseurl-1.3.3" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.3.tgz";
        sha512 = "CiyeOxFT/JZyN5m0z9PfXw4SCBJ6Sygz1Dpl0wqjlhDEGGBP1GnsUVEL0p63hoG1fcj3fHynXi9NYO4nWOL+qQ==";
      };
    };
    "pause-0.0.1" = {
      name = "pause";
      packageName = "pause";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pause/-/pause-0.0.1.tgz";
        sha1 = "1d408b3fdb76923b9543d96fb4c9dfd535d9cb5d";
      };
    };
    "policyfile-0.0.4" = {
      name = "policyfile";
      packageName = "policyfile";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/policyfile/-/policyfile-0.0.4.tgz";
        sha1 = "d6b82ead98ae79ebe228e2daf5903311ec982e4d";
      };
    };
    "qs-0.6.6" = {
      name = "qs";
      packageName = "qs";
      version = "0.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-0.6.6.tgz";
        sha1 = "6e015098ff51968b8a3c819001d5f2c89bc4b107";
      };
    };
    "range-parser-0.0.4" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-0.0.4.tgz";
        sha1 = "c0427ffef51c10acba0782a46c9602e744ff620b";
      };
    };
    "raw-body-1.1.2" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-1.1.2.tgz";
        sha1 = "c74b3004dea5defd1696171106ac740ec31d62be";
      };
    };
    "readable-stream-1.0.34" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.0.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz";
        sha1 = "125820e34bc842d2f2aaafafe4c2916ee32c157c";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "redis-0.7.3" = {
      name = "redis";
      packageName = "redis";
      version = "0.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis/-/redis-0.7.3.tgz";
        sha1 = "ee57b7a44d25ec1594e44365d8165fa7d1d4811a";
      };
    };
    "sanitizer-0.1.3" = {
      name = "sanitizer";
      packageName = "sanitizer";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sanitizer/-/sanitizer-0.1.3.tgz";
        sha1 = "d4f0af7475d9a7baf2a9e5a611718baa178a39e1";
      };
    };
    "semver-1.1.4" = {
      name = "semver";
      packageName = "semver";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-1.1.4.tgz";
        sha1 = "2e5a4e72bab03472cc97f72753b4508912ef5540";
      };
    };
    "send-0.1.4" = {
      name = "send";
      packageName = "send";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.1.4.tgz";
        sha1 = "be70d8d1be01de61821af13780b50345a4f71abd";
      };
    };
    "socket.io-0.9.16" = {
      name = "socket.io";
      packageName = "socket.io";
      version = "0.9.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io/-/socket.io-0.9.16.tgz";
        sha1 = "3bab0444e49b55fbbc157424dbd41aa375a51a76";
      };
    };
    "socket.io-client-0.9.16" = {
      name = "socket.io-client";
      packageName = "socket.io-client";
      version = "0.9.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/socket.io-client/-/socket.io-client-0.9.16.tgz";
        sha1 = "4da7515c5e773041d1b423970415bcc430f35fc6";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha1 = "161c7dac177659fd9811f43771fa99381478628c";
      };
    };
    "stream-counter-0.2.0" = {
      name = "stream-counter";
      packageName = "stream-counter";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-counter/-/stream-counter-0.2.0.tgz";
        sha1 = "ded266556319c8b0e222812b9cf3b26fa7d947de";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "tinycolor-0.0.1" = {
      name = "tinycolor";
      packageName = "tinycolor";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinycolor/-/tinycolor-0.0.1.tgz";
        sha1 = "320b5a52d83abb5978d81a3e887d4aefb15a6164";
      };
    };
    "uglify-js-1.2.5" = {
      name = "uglify-js";
      packageName = "uglify-js";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/uglify-js/-/uglify-js-1.2.5.tgz";
        sha1 = "b542c2c76f78efb34b200b20177634330ff702b6";
      };
    };
    "uid2-0.0.3" = {
      name = "uid2";
      packageName = "uid2";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid2/-/uid2-0.0.3.tgz";
        sha1 = "483126e11774df2f71b8b639dcd799c376162b82";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "utils-merge-1.0.1" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz";
        sha1 = "9f95710f50a267947b2ccc124741c1028427e713";
      };
    };
    "ws-0.4.32" = {
      name = "ws";
      packageName = "ws";
      version = "0.4.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-0.4.32.tgz";
        sha1 = "787a6154414f3c99ed83c5772153b20feb0cec32";
      };
    };
    "xmlhttprequest-1.4.2" = {
      name = "xmlhttprequest";
      packageName = "xmlhttprequest";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlhttprequest/-/xmlhttprequest-1.4.2.tgz";
        sha1 = "01453a1d9bed1e8f172f6495bbf4c8c426321500";
      };
    };
    "zeparser-0.0.5" = {
      name = "zeparser";
      packageName = "zeparser";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/zeparser/-/zeparser-0.0.5.tgz";
        sha1 = "03726561bc268f2e5444f54c665b7fd4a8c029e2";
      };
    };
  };
  args = {
    name = "mediengewitter";
    packageName = "mediengewitter";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."active-x-obfuscator-0.0.1"
      sources."async-0.1.15"
      sources."base64id-0.1.0"
      sources."batch-0.5.0"
      sources."buffer-crc32-0.2.1"
      sources."bytes-0.2.1"
      sources."commander-2.1.0"
      sources."connect-3.7.0"
      sources."connect-cache-0.2.2"
      sources."cookie-0.1.0"
      sources."cookie-signature-1.0.1"
      sources."core-util-is-1.0.2"
      sources."debug-2.6.9"
      sources."ee-first-1.1.1"
      sources."encodeurl-1.0.2"
      sources."escape-html-1.0.3"
      (sources."express-3.4.7" // {
        dependencies = [
          sources."commander-1.3.2"
          sources."connect-2.12.0"
          sources."debug-0.8.1"
        ];
      })
      sources."finalhandler-1.1.2"
      sources."fresh-0.2.0"
      sources."inherits-2.0.4"
      sources."isarray-0.0.1"
      sources."js-md5-0.4.2"
      sources."keypress-0.1.0"
      sources."log4js-0.6.9"
      sources."merge-descriptors-0.0.1"
      sources."methods-0.1.0"
      sources."mime-1.2.11"
      sources."mkdirp-0.3.5"
      sources."ms-2.0.0"
      (sources."multiparty-2.2.0" // {
        dependencies = [
          sources."readable-stream-1.1.14"
        ];
      })
      sources."nan-1.0.0"
      sources."negotiator-0.3.0"
      sources."on-finished-2.3.0"
      sources."options-0.0.6"
      sources."parseurl-1.3.3"
      sources."pause-0.0.1"
      sources."policyfile-0.0.4"
      sources."qs-0.6.6"
      sources."range-parser-0.0.4"
      sources."raw-body-1.1.2"
      sources."readable-stream-1.0.34"
      sources."redis-0.7.3"
      sources."sanitizer-0.1.3"
      sources."semver-1.1.4"
      sources."send-0.1.4"
      sources."socket.io-0.9.16"
      sources."socket.io-client-0.9.16"
      sources."statuses-1.5.0"
      (sources."stream-counter-0.2.0" // {
        dependencies = [
          sources."readable-stream-1.1.14"
        ];
      })
      sources."string_decoder-0.10.31"
      sources."tinycolor-0.0.1"
      sources."uglify-js-1.2.5"
      sources."uid2-0.0.3"
      sources."unpipe-1.0.0"
      sources."utils-merge-1.0.1"
      sources."ws-0.4.32"
      sources."xmlhttprequest-1.4.2"
      sources."zeparser-0.0.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}